version: "3"

services:
  api:
    build:
      context: .
      target: prod
      args:
        - NODE_ENV=production
    ports:
      - 8080:3000
      - 443:3000
      - 80:3000
    command: npm run start
