version: "3"

services:
  api:
    build:
      context: .
      target: dev
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: npm run dev
