version: "3"

services:
  api:
    build: .
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
    command: npm run start

    ports:
          - 8080:3000
          - 443:3000
          - 80:3000    

